export interface BangChamCong {
    code?:	string,
    ngayThem?:	Date,
    ngayChinhSua?:	Date,
    nguoiThem?:	string,
    nguoiChinhSua?:	string,
    suDung?:	number,
    ma_ChiNhanh?:	string,
    ma_NhanVien?:	string,
    ngay?:	Date,
    nghiCoPhep?:	boolean,
    gioDen?:	number,
    gioVe?:	number,
    gioLamThem?:	number,
    gioMuon?:	number,
}